import 'package:camera/camera.dart';
import 'package:e_point/cubit/cubit.dart';
// import 'package:e_point/cubit/foul_category_cubit.dart';
import 'package:e_point/main.dart';
import 'package:e_point/models/models.dart';
import 'package:e_point/shared/shared.dart';
import 'package:e_point/ui/widgets/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:supercharged/supercharged.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'general_page.dart';
part 'signin_page.dart';
part 'main_page.dart';
part 'home_page.dart';
part 'punishment_page.dart';
part 'profile_page.dart';
part 'rules_page.dart';
part 'home_page_teacher.dart';
part 'main_page_teacher.dart';
part 'student.dart';
part 'students_page.dart';
part 'detail_student.dart';
// part '../widgets/menu.dart';
// part '../widgets/menu.dart';
